/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package techmasterminds.robs.feedback;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import techmasterminds.robs.MonthlyExpenditures.MonthlyExpenditures;
import techmasterminds.robs.expensetracker.ExpenseTracker;
import techmasterminds.robs.studentInfo.StudentInfo;

/**
 *
 * @author bontl
 */
public class FeedBack extends javax.swing.JFrame {

    /**
     * Creates new form DisplayMonthly
     */
       private ExpenseTracker Expenses;
       private StudentInfo student;
    public FeedBack(String month) {
        initComponents();
           
           File studentDetailsFile = new File("DetailsList.txt");
   
    try (BufferedReader reader = new BufferedReader(new FileReader(studentDetailsFile))) {
        String line = reader.readLine();
        if (line != null) {
            String[] parts = line.split("#");
            String name = parts[0];
            String surname = parts[1];
            String institution = parts[2];
            String studentNumber = parts[3];
            boolean hasFunding = Boolean.parseBoolean(parts[4]);
            int allowance = Integer.parseInt(parts[5]);
            
           student = new StudentInfo(name, surname, institution, studentNumber, hasFunding, allowance);
            Expenses = new ExpenseTracker(student);
           
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Could not read student details.");
        return;
    } 
     double totalExpenses= 0;
     String ExpenseList = "";
    
   try (BufferedReader reader = new BufferedReader(new FileReader("Expenses.txt"))) {
            String line = reader.readLine();
            while (line != null) {
                // Correctly escape the $ symbol
                String[] parts = line.split("\\$");
                String expenseName = parts[0];
                double expenseAmount = Double.parseDouble(parts[1]);
                totalExpenses += expenseAmount;

                // Append to the list instead of overwriting
                ExpenseList += expenseName + ":  R" + expenseAmount + "\n";

                line = reader.readLine();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Could not read expenses.");
            return;
        }

         TextAreaSum.setText(Expenses.Summary(ExpenseList, totalExpenses, month));
       
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaSum = new javax.swing.JTextArea();
        JButExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Monthly Expenses ");

        TextAreaSum.setColumns(20);
        TextAreaSum.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 14)); // NOI18N
        TextAreaSum.setRows(5);
        jScrollPane1.setViewportView(TextAreaSum);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JButExit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JButExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techmasterminds/robs/feedback/job.png"))); // NOI18N
        JButExit.setText("Exit");
        JButExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButExitActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techmasterminds/robs/feedback/add.png"))); // NOI18N
        jButton1.setText("New month");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(220, 220, 220)
                .addComponent(JButExit)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(JButExit))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     TextAreaSum.setText("");
     new MonthlyExpenditures().setVisible(true);
     this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JButExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButExitActionPerformed
System.exit(0);       
    }//GEN-LAST:event_JButExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedBack("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButExit;
    private javax.swing.JTextArea TextAreaSum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
