/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package techmasterminds.robs.details;

import javax.swing.JOptionPane;
import techmasterminds.robs.MonthlyExpenditures.MonthlyExpenditures;
import techmasterminds.robs.expensetracker.ExpenseTracker;
import techmasterminds.robs.studentInfo.StudentInfo;
import java.io.File;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;


public class AddDetails extends javax.swing.JFrame {

    /**
     * Creates new form AddDetails
     */
    
    public AddDetails() {
        initComponents();

 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTextName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTextSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JtextStudNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JCombFunding = new javax.swing.JComboBox<>();
        JsaveButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JTextUni = new javax.swing.JTextField();
        JAllowanaceLab = new javax.swing.JLabel();
        JallowanceSpin = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Enter Your Details");

        JTextName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Enter Your Name: ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Enter Your Surname:");

        JTextSurname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JTextSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextSurnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Enter Your Student Number:");

        JtextStudNum.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JtextStudNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextStudNumActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Do You Have Student Funding?");

        JCombFunding.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JCombFunding.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        JCombFunding.setToolTipText("");

        JsaveButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JsaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techmasterminds/robs/details/save.png"))); // NOI18N
        JsaveButton.setText("Save");
        JsaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JsaveButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Institution:");

        JTextUni.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JTextUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextUniActionPerformed(evt);
            }
        });

        JAllowanaceLab.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JAllowanaceLab.setText("Please enter your monthly allowance:");

        JallowanceSpin.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JallowanceSpin.setModel(new javax.swing.SpinnerNumberModel(100, 0, 10000000, 100));
        JallowanceSpin.setName(""); // NOI18N
        JallowanceSpin.setValue(100);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(JsaveButton)
                            .addComponent(jLabel4)
                            .addComponent(JAllowanaceLab)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTextName)
                            .addComponent(JTextSurname)
                            .addComponent(JtextStudNum)
                            .addComponent(JTextUni)
                            .addComponent(JCombFunding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JallowanceSpin))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTextSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtextStudNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JallowanceSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JAllowanaceLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(JCombFunding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(JsaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techmasterminds/robs/details/job.png"))); // NOI18N
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextNameActionPerformed

    private void JTextSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextSurnameActionPerformed

    private void JtextStudNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextStudNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextStudNumActionPerformed
     public static void saveDetailsFile(File StudentDetailsList, String StudentDetails) throws IOException
     {    
    BufferedWriter bw = new BufferedWriter(new FileWriter(StudentDetailsList, false));
    bw.write(StudentDetails);  
    bw.close();
       }
    
     
    private void JsaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsaveButtonActionPerformed
         String name = JTextName.getText();
      String surname = JTextSurname.getText();
      String studentNum = JtextStudNum.getText();
      String institution = JTextUni.getText();
       
          int monthlyAllowance = (int) JallowanceSpin.getValue();
      String selected = JCombFunding.getSelectedItem().toString();
      boolean hasFunding = selected.equalsIgnoreCase("Yes");
      StudentInfo Student = new StudentInfo(name, surname, institution,studentNum, hasFunding, monthlyAllowance );   
        ExpenseTracker Details = new ExpenseTracker(Student);
        
       if (Student.hasBursary())
           Student.setMonthlyAllowance(monthlyAllowance + 1500);
        
        
    File StudentDetailList = new File("DetailsList.txt");    
    try
    {
   saveDetailsFile(StudentDetailList , Student.ToString());
    }
    catch(IOException e)
    {
    System.out.println("The data could not be saved to the file");
    }
      JsaveButton.setVisible(false);
 
    }//GEN-LAST:event_JsaveButtonActionPerformed

    private void JTextUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextUniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextUniActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MonthlyExpenditures().setVisible(true);
       setVisible(false);
     
       JOptionPane.showMessageDialog(this, "Enter the expenses you had for this month and the amount you spent\nOnce complete click on the 'Display Feedback' button e.g\nExpense: Food   Amount: R1200\nExpense: Entertainment   Amount: R7000");          

   
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           // java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JAllowanaceLab;
    private javax.swing.JComboBox<String> JCombFunding;
    private javax.swing.JTextField JTextName;
    private javax.swing.JTextField JTextSurname;
    private javax.swing.JTextField JTextUni;
    private javax.swing.JSpinner JallowanceSpin;
    private javax.swing.JButton JsaveButton;
    private javax.swing.JTextField JtextStudNum;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
